feat: add stop pushing rule

diff --git a/bin/git-__push-with-check b/bin/git-__push-with-check
--- a/bin/git-__push-with-check
+++ b/bin/git-__push-with-check
@@ -1,5 +1,10 @@
 #!/usr/bin/env sh
 
+if git current-branch | grep -i "wip"; then
+  # display error message in red
+  echo -e "\n\033[31mError: Found 'wip' in branch name. Please fix before pushing.\033[0m"
+  exit 1
+fi
 if git log origin/$(git rev-parse --abbrev-ref HEAD)..HEAD --oneline | grep -i "wip"; then
   # display error message in red
   echo -e "\n\033[31mError: Found 'wip' in local commit. Please fix before pushing.\033[0m"
